version: 2.1

orbs:
  rn: react-native-community/react-native@1.2.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run validate:eslint
      - run:
          name: Flow
          command: yarn run validate:flow
      - run:
          name: Jest
          command: yarn run test:jest
  publish:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Add Github to known hosts
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - run:
          name: Publish to NPM
          command: yarn semantic-release

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      # - rn/android_build:
      #     name: build_android_debug
      #     project_path: "example/android"
      #     build_type: debug
      #     requires:
      #       - analyse
      # - rn/android_build:
      #     name: build_android_release
      #     project_path: "example/android"
      #     build_type: release
      #     requires:
      #       - analyse
      # - rn/android_test:
      #     logcat_grep: "com.geolocationexample"
      #     detox_configuration: "android.emu.release"
      #     detox_loglevel: verbose
      #     requires:
      #       - build_android_release
      # - rn/ios_build_and_test:
      #     project_path: "example/ios/GeolocationExample.xcodeproj"
      #     derived_data_path: "example/ios/build"
      #     device: "iPhone X"
      #     build_configuration: "Release"
      #     scheme: "GeolocationExample"
      #     detox_configuration: "ios.sim.release"
      #     detox_loglevel: verbose
      #     requires:
      #       - analyse
      - publish:
          requires:
            - analyse
            # - rn/android_test
            # - rn/ios_build_and_test
          filters:
            branches:
              only: master
